application: delta-trees-830
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  max_idle_instances: 20

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /third_party/vis
  static_dir: third_party/vis

- url: /
  static_files: index.html
  upload: index\.html

- url: /.*
  script: main.APP

libraries:
- name: ssl
  version: latest
- name: pycrypto
  version: latest
- name: jinja2
  version: latest
