application: delta-trees-830
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  max_idle_instances: 20

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /poll_gce/.*
  script: poll_gce.APP

- url: /callback(/.*)?
  script: callback.APP

- url: /stage(/.*)
  script: stage_status.APP

- url: /cleanup(/.*)
  script: stage_status.APP

- url: /run_stages/?
  script: run_stages.APP

- url: /test_results/.*
  script: test_results.APP

- url: /view_stages/?
  script: view_stages.APP

- url: /timeline/?
  script: timeline.APP

- url: /.*
  script: printenv.APP

libraries:
- name: ssl
  version: latest
- name: pycrypto
  version: latest
- name: jinja2
  version: latest
